apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jupyterlab-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-05b0878594b65b722
  accessPointId: fsap-0d6696f5b0ec83465  # Use the new Access Point ID for JupyterLab
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
mountOptions:
  - tls
volumeBindingMode: WaitForFirstConsumer
